fork = false

[font]
size = 12
hinting = "full"
edging = "antialias"

[font.features]
"Monaspace Neon" = [
  "+calt", "+liga", "+zero", "+ss01", "+ss02", "+ss03", "+ss04", "+ss05",
  "+ss06", "+ss07", "+ss08", "+ss09", "+ss10", "+cv01", "+cv02", "-cv10",
  "-cv11", "+cv30", "+cv31", "-cv32", "-cv60", "-cv61", "-cv62",
]


[[font.normal]]
# family = "MonoLisaCustom Nerd Font"
family = "Monaspace Neon"

[box-drawing]
mode = "native"

[box-drawing.sizes]
default = [1,3]
